CREATE OR REPLACE VIEW LOCATION_VIEW
AS SELECT PROVINCES.PROVINCE_NAME, ADDRESS.CITY
FROM PROVINCES, ADDRESS WHERE PROVINCES.PROVINCE_ID = ADDRESS.PROVINCE_ID;

CREATE OR REPLACE VIEW CUSTOMER_VIEW
AS SELECT CUSTOMERS.CUSTOMER_NAME, CUSTOMERS.CUSTOMER_SURNAME, ADDRESS.STREET_NAME, ADDRESS.STREET_NUMBER
FROM CUSTOMERS, ADDRESS WHERE CUSTOMERS.ADDRESS_ID = ADDRESS.ADDRESS_ID;

CREATE OR REPLACE VIEW REPAIRSTATUS_VIEW
AS SELECT REPAIRS.REPAIR_ID, STATUS.STATUS_NAME
FROM REPAIRS, STATUS WHERE STATUS.STATUS_ID = REPAIRS.STATUS_ID;

CREATE OR REPLACE VIEW TECHNICIANS_VIEW
AS SELECT REPAIRS.REPAIR_ID, TECHNICIANS.TECH_NAME, TECHNICIANS.TECH_SURNAME
FROM REPAIRS, TECHNICIANS WHERE REPAIRS.TECHNICIAN_ID = TECHNICIANS.TECHNICIAN_ID;

CREATE OR REPLACE VIEW ORDERPARTS_VIEW
AS SELECT O.ORDER_ID, P.PART_NAME, P.PART_TYPE, P.PART_COST
FROM ORDERS O
JOIN PARTS_IN_ORDER PIO ON O.ORDER_ID = PIO.ORDER_ID
JOIN PARTS P ON PIO.PARTS_ID = P.PART_ID;

CREATE OR REPLACE VIEW REPAIRPARTS_VIEW
AS SELECT R.REPAIR_ID, P.PART_NAME, P.PART_TYPE, P.PART_COST
FROM REPAIRS R
JOIN PARTS_IN_REPAIR PIR ON R.REPAIR_ID = PIR.REPAIR_ID
JOIN PARTS P ON PIR.PART_ID = P.PART_ID;
