CREATE VIEW LOCATION_VIEW
AS SELECT PROVINCES.PROVINCE_NAME, ADDRESS.CITY
FROM PROVINCES, ADDRESS WHERE PROVINCES.PROVINCE_ID = ADDRESS.PROVINCE_ID;

CREATE VIEW CUSTOMER_VIEW
AS SELECT CUSTOMERS.CUSTOMER_NAME, CUSTOMERS.CUSTOMER_SURNAME, ADDRESS.STREET_NAME, ADDRESS.STREET_NUMBER
FROM CUSTOMERS, ADDRESS WHERE CUSTOMERS.ADDRESS_ID = ADDRESS.ADDRESS_ID;

CREATE VIEW REPAIRSTATUS_VIEW
AS SELECT REPAIRS.REPAIR_ID, STATUS.STATUS_NAME
FROM REPAIRS, STATUS WHERE STATUS.STATUS_ID = REPAIRS.STATUS_ID;

CREATE VIEW TECHNICIANS_VIEW
AS SELECT REPAIRS.REPAIR_ID, TECHNICIANS.TECH_NAME, TECHNICIANS.TECH_SURNAME
FROM REPAIRS, TECHNICIANS WHERE REPAIRS.TECHNICIAN_ID = TECHNICIANS.TECHNICIAN_ID;

CREATE VIEW ORDERPARTS_VIEW
AS SELECT ORDERS.ORDER_ID, PARTS.PART_NAME, PARTS.PART_TYPE, PARTS.PART_COST
FROM ORDERS, PARTS WHERE PARTS.PART_ID = ORDERS.PART_ID;
