-----------
--QUERIES
-----------
--Add Orders
INSERT INTO ORDERS VALUES (ORDER_ID_value.nextval, '&CUSTOMER_ID', '&TECHNICIAN_ID', '&ORDER_DATE', '&ORDER_STATUS', ROUND((SELECT SUM(p.PART_COST) FROM PARTS p JOIN PARTS_IN_ORDER i ON p.PART_ID = i.PARTS_ID JOIN ORDERS o ON o.ORDER_ID = i.ORDER_ID WHERE o.ORDER_ID = ORDER_ID_value GROUP BY o.ORDER_ID)*1.10, 2));

--Update Orders
UPDATE ORDERS SET ORDER_STATUS = '&ORDER_STATUS' WHERE ORDER_ID = '&ORDER_ID';

--Add Rerpair
INSERT INTO REPAIRS VALUES (REPAIR_ID_value.nextval, '&CUSTOMER_ID', '&TECHNICIAN_ID', '&STATUS_ID', '&ADDRESS_ID', '&REPAIR_DATE', ROUND((SELECT SUM(p.PART_COST) FROM PARTS p JOIN PARTS_IN_REPAIR i ON p.PART_ID = i.PART_ID JOIN REPAIRS r ON r.REPAIR_ID = i.REPAIR_ID WHERE r.REPAIR_ID = REPAIR_ID_value GROUP BY r.REPAIR_ID)*1.10, 2));

--Update Repair
UPDATE REPAIRS SET STATUS_ID = '&STATUS_ID', REPAIR_DATE = '&REPAIR_DATE' WHERE REPAIR_ID = '&REPAIR_ID';

--Add PartS
INSERT INTO PARTS VALUES (PART_ID_value.nextval, '&PART_NAME', '&PART_BRAND', '&PART_TYPE', '&PART_COST', '&PARTS_IN_STOCK');

--Update Parts
UPDATE PARTS SET PART_COST = '&PART_COST', PARTS_IN_STOCK = '&PARTS_IN_STOCK' WHERE PART_ID = '&PART_ID';
