--------------------------------------------------------
--  File created - Friday-May-17-2024   
--------------------------------------------------------
CREATE INDEX TECH_NAMESURNAME_IDX ON TECHNICIANS (TECH_NAME, TECH_SURNAME);
CREATE INDEX PARTS_COSTTYPE_IDX ON PARTS (PART_COST, PART_TYPE);
CREATE INDEX CUSTOMERS_FULLNAME_IDX ON CUSTOMERS (CUSTOMER_NAME, CUSTOMER_SURNAME);
CREATE INDEX ADDRESS_STREET_IDX ON ADDRESS (STREET_NAME, STREET_NUMBER);
CREATE INDEX DEPART_CAPACITY_IDX ON DEPARTMENTS (DEPARTMENT_WORK_CAPACITY DESC);
CREATE INDEX ORDER_STATUSDATE_IDX ON ORDERS (ORDER_STATUS, ORDER_DATE);
CREATE INDEX PROVINCE_NAME_IDX ON PROVINCES (PROVINCE_NAME);
CREATE INDEX REPAIR_STATUSDATE_IDX ON REPAIRS (REPAIR_DATE, STATUS_ID);