-----------------------------------------------------------
--Data Insert
-----------------------------------------------------------
--Provinces
INSERT INTO PROVINCES (PROVINCE_ID, PROVINCE_NAME) VALUES
(PROVINCE_ID_VALUE.nextval, 'Eastern Cape');
INSERT INTO PROVINCES (PROVINCE_ID, PROVINCE_NAME) VALUES
(PROVINCE_ID_VALUE.nextval, 'Free State');
INSERT INTO PROVINCES (PROVINCE_ID, PROVINCE_NAME) VALUES
(PROVINCE_ID_VALUE.nextval, 'Gauteng');
INSERT INTO PROVINCES (PROVINCE_ID, PROVINCE_NAME) VALUES
(PROVINCE_ID_VALUE.nextval, 'KwaZulu-Natal');
INSERT INTO PROVINCES (PROVINCE_ID, PROVINCE_NAME) VALUES
(PROVINCE_ID_VALUE.nextval, 'Limpopo');
INSERT INTO PROVINCES (PROVINCE_ID, PROVINCE_NAME) VALUES
(PROVINCE_ID_VALUE.nextval, 'Mpumalanga');
INSERT INTO PROVINCES (PROVINCE_ID, PROVINCE_NAME) VALUES
(PROVINCE_ID_VALUE.nextval, 'Northern Cape');
INSERT INTO PROVINCES (PROVINCE_ID, PROVINCE_NAME) VALUES
(PROVINCE_ID_VALUE.nextval, 'North West');
INSERT INTO PROVINCES (PROVINCE_ID, PROVINCE_NAME) VALUES
(PROVINCE_ID_VALUE.nextval, 'Western Cape');
--


-- Status
INSERT INTO STATUS (STATUS_ID, STATUS_NAME) VALUES
(STATUS_ID_VALUE.nextval, 'In Transit');
INSERT INTO STATUS (STATUS_ID, STATUS_NAME) VALUES
(STATUS_ID_VALUE.nextval, 'In Progress');
INSERT INTO STATUS (STATUS_ID, STATUS_NAME) VALUES
(STATUS_ID_VALUE.nextval, 'Completed');
INSERT INTO STATUS (STATUS_ID, STATUS_NAME) VALUES
(STATUS_ID_VALUE.nextval, 'To Do');
INSERT INTO STATUS (STATUS_ID, STATUS_NAME) VALUES
(STATUS_ID_VALUE.nextval, 'Standby');
--

-- Departments
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES
(DEPARTMENT_ID_VALUE.nextval, 'Customer Service Representatives');
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES
(DEPARTMENT_ID_VALUE.nextval, 'Technicians');
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES
(DEPARTMENT_ID_VALUE.nextval, 'Sales and Marketing Personnel');
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES
(DEPARTMENT_ID_VALUE.nextval, 'IT Personnel');
--

--ADDRESS
INSERT INTO address
VALUES (ADDRESS_ID_VALUE.nextval,'8th street',20,'Polokwane',5);
INSERT INTO address
VALUES (ADDRESS_ID_VALUE.nextval,'5th street',8,'Stofberg',2);
INSERT INTO address
VALUES (ADDRESS_ID_VALUE.nextval,'7th street',99,'Pretoria',3);
--


--Customers
INSERT INTO customers
VALUES (CUSTOMER_ID_VALUE.nextval, 'customer@email.com','0661024086','Fanie','Van Vuuren',1);
INSERT INTO customers
VALUES (CUSTOMER_ID_VALUE.nextval, 'customer2@email.com','0715896321','Ben','Van Vuuren',2);
INSERT INTO customers
VALUES (CUSTOMER_ID_VALUE.nextval, 'customer3@email.com','0324928569','Veronica','Van Vuuren',3);
--

--Parts
INSERT INTO PARTS
VALUES (PART_ID_VALUE.nextval,'RTX 3060','Nvidea','Graphics Card', 40000,20);
INSERT INTO PARTS
VALUES (PART_ID_VALUE.nextval,'GTX 1020','Nvidea','Graphics Card', 4000,14);
INSERT INTO PARTS
VALUES (PART_ID_VALUE.nextval,'GTX 1060 TI','Nvidea','Graphics Card', 8000,8);
INSERT INTO PARTS
VALUES (PART_ID_VALUE.nextval,'I3 400Hz','Intel','CPU', 1000,3);
--

--Technicians
INSERT INTO TECHNICIANS
VALUES (TECHNICIAN_ID_VALUE.nextval,1,'Burger',0412589636,'Franco',2);
INSERT INTO TECHNICIANS
VALUES (TECHNICIAN_ID_VALUE.nextval,0,'Ricon',4589637845,'David',4);
INSERT INTO TECHNICIANS
VALUES (TECHNICIAN_ID_VALUE.nextval,1,'Smith',0152364150,'Steven',2);
--

--Order

INSERT INTO ORDERS
VALUES (ORDER_ID_VALUE.nextval,1,1,'01-Jan-23',5,0);
INSERT INTO PARTS_IN_ORDER
VALUES (PIO_ID_VALUE.nextval,1,1);
UPDATE ORDERS
SET total_cost = (SELECT PART_COST FROM PARTS WHERE PART_ID = 1)*1.1
WHERE ORDER_ID = '1';


INSERT INTO ORDERS
VALUES (ORDER_ID_VALUE.nextval,2,3,'10-Jan-23',5,0);
INSERT INTO PARTS_IN_ORDER
VALUES (PIO_ID_VALUE.nextval,2,2);
UPDATE ORDERS
SET total_cost = (SELECT PART_COST FROM PARTS WHERE PART_ID = 2)*1.1
WHERE ORDER_ID = '2';

INSERT INTO ORDERS
VALUES (ORDER_ID_VALUE.nextval,3,2,'15-Jan-23',5,0);
INSERT INTO PARTS_IN_ORDER
VALUES (PIO_ID_VALUE.nextval,3,1);
UPDATE ORDERS
SET total_cost = (SELECT PART_COST FROM PARTS WHERE PART_ID = 1)*1.1
WHERE ORDER_ID = '3';

--Repair

INSERT INTO REPAIRS
VALUES (REPAIR_ID_VALUE.nextval,1,1,5,(SELECT ADDRESS_ID FROM CUSTOMERS WHERE CUSTOMER_ID = '1'),'01-Jan-23',0);
INSERT INTO PARTS_IN_REPAIR
VALUES (PIR_ID_VALUE.nextval,1,1);
UPDATE REPAIRS
SET ACCUMULATED_COST = (SELECT PART_COST FROM PARTS WHERE PART_ID = '1')*1.1
WHERE REPAIR_ID = '1';

INSERT INTO REPAIRS
VALUES (REPAIR_ID_VALUE.nextval,3,2,5,(SELECT ADDRESS_ID FROM CUSTOMERS WHERE CUSTOMER_ID = '3'),'01-Jan-23',0);
INSERT INTO PARTS_IN_REPAIR
VALUES (PIR_ID_VALUE.nextval,2,3);
UPDATE REPAIRS
SET ACCUMULATED_COST = (SELECT PART_COST FROM PARTS WHERE PART_ID = '3')*1.1
WHERE REPAIR_ID = '2';

INSERT INTO REPAIRS
VALUES (REPAIR_ID_VALUE.nextval,2,3,5,(SELECT ADDRESS_ID FROM CUSTOMERS WHERE CUSTOMER_ID = '1'),'01-Jan-23',0);
INSERT INTO PARTS_IN_REPAIR
VALUES (PIR_ID_VALUE.nextval,3,4);
UPDATE REPAIRS
SET ACCUMULATED_COST = (SELECT PART_COST FROM PARTS WHERE PART_ID = '4')*1.1
WHERE REPAIR_ID = '3';
