--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "FANIE"."CUSTOMERS" 
   (	"CUSTOMER_ID" NUMBER(*,0), 
	"CUSTOMER_EMAIL" VARCHAR2(30 BYTE), 
	"CUSTOMER_PHONE_NUMBER" VARCHAR2(10 BYTE), 
	"CUSTOMER_NAME" VARCHAR2(25 BYTE), 
	"CUSTOMER_SURNAME" VARCHAR2(25 BYTE), 
	"ADDRESS_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "FANIE"."CUSTOMERS"."ADDRESS_ID" IS 'Links to Adress Table';
