--------------------------------------------------------
--  File created - Wednesday-May-15-2024   
--------------------------------------------------------
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\ADDRESS.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\CUSTOMERS.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\DEPARTMENTS.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\ORDERS.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\PARTS.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\PARTS_IN_ORDER.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\PARTS_IN_REPAIR.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\PROVINCES.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\REPAIR_ORDER.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\STATUS.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\TECHNICIANS.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\ADDRESS_DATA_TABLE.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\CUSTOMERS_DATA_TABLE.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\DEPARTMENTS_DATA_TABLE.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\ORDERS_DATA_TABLE.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\PARTS_DATA_TABLE.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\PARTS_IN_ORDER_DATA_TABLE.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\PARTS_IN_REPAIR_DATA_TABLE.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\PROVINCES_DATA_TABLE.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\REPAIR_ORDER_DATA_TABLE.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\STATUS_DATA_TABLE.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\TECHNICIANS_DATA_TABLE.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\TECHNICIANS_PK.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\DEPARTMENTS_PK.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\ADDRESS_PK.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\CUSTOMERS_PK.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\REPAIR_ORDER_PK.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\PARTS_PK.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\STATUS_PK.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\PROVINCES_PK.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\ORDERS_PK.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\PROVINCES_CONSTRAINT.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\REPAIR_ORDER_CONSTRAINT.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\ORDERS_CONSTRAINT.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\DEPARTMENTS_CONSTRAINT.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\STATUS_CONSTRAINT.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\PARTS_CONSTRAINT.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\PARTS_IN_REPAIR_CONSTRAINT.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\CUSTOMERS_CONSTRAINT.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\TECHNICIANS_CONSTRAINT.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\PARTS_IN_ORDER_CONSTRAINT.sql
@C:\Users\jaund\Downloads\GitAttempt\Cache-Crusaders\DBStuff\ADDRESS_CONSTRAINT.sql
