REM INSERTING into FANIE.PROVINCES
SET DEFINE OFF;
Insert into FANIE.PROVINCES (PROVINCE_ID,PROVINCE_NAME) values (1,'Eastern Cape');
Insert into FANIE.PROVINCES (PROVINCE_ID,PROVINCE_NAME) values (2,'Free State');
Insert into FANIE.PROVINCES (PROVINCE_ID,PROVINCE_NAME) values (3,'Gauteng');
Insert into FANIE.PROVINCES (PROVINCE_ID,PROVINCE_NAME) values (4,'KwaZulu-Natal');
Insert into FANIE.PROVINCES (PROVINCE_ID,PROVINCE_NAME) values (5,'Limpopo');
Insert into FANIE.PROVINCES (PROVINCE_ID,PROVINCE_NAME) values (6,'Mpumalanga');
Insert into FANIE.PROVINCES (PROVINCE_ID,PROVINCE_NAME) values (7,'Northern Cape');
Insert into FANIE.PROVINCES (PROVINCE_ID,PROVINCE_NAME) values (8,'North West');
Insert into FANIE.PROVINCES (PROVINCE_ID,PROVINCE_NAME) values (9,'Western Cape');
