--------------------------------------------------------
--  DDL for Table TECHNICIANS
--------------------------------------------------------

  CREATE TABLE "FANIE"."TECHNICIANS" 
   (	"TECHNICIAN_ID" NUMBER(*,0), 
	"AVAILABILITY" NUMBER(*,0), 
	"TECH_SURNAME" VARCHAR2(25 BYTE), 
	"TECH_PHONE_NUMBER" VARCHAR2(10 BYTE), 
	"TECH_NAME" VARCHAR2(25 BYTE), 
	"DEPARTMENT_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "FANIE"."TECHNICIANS"."AVAILABILITY" IS 'Each department role has a set max jobs, this is each user''s current jobs count';
   COMMENT ON COLUMN "FANIE"."TECHNICIANS"."DEPARTMENT_ID" IS 'Needs FK implemented';
